spring:
  datasource:
    username: root
    password: Emat1234
    url: jdbc:mysql://localhost:3306/activiti-start?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Hongkong&nullCatalogMeansCurrent=true
#  resources:
#    static-locations: file:E:\workSpace\web\design\webapp
  mvc:
    servlet:
      path: /app
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update

    show-sql: true
  liquibase:
    change-log: classpath:activiti-app-db-changelog.xml
